// frontend/src/App.tsx
import { useLocation } from 'react-router-dom';

import { LoginModal } from '@/components/auth/LoginModal';
import { AppHeader } from '@/components/common/AppHeader';
import { useImageDetailModalState } from '@/hooks/useImageDetailModalState';
import { cn } from '@/lib/utils';
import { AppRoutes } from '@/router';

export function App() {
  const location = useLocation();
  const isLanding = location.pathname === '/';
  const { isImageDetailModalOpen } = useImageDetailModalState();
  return (
    <div className={cn('app-shell', isLanding && 'app-shell--landing')}>
      {!isLanding && !isImageDetailModalOpen ? <AppHeader /> : null}
      <main
        className={cn('app-main', isLanding && 'app-main--landing')}
        aria-label={isLanding ? 'Nebulens 首页' : 'Nebulens 工作区'}
      >
        <div className={cn('app-workspace', !isLanding && 'app-workspace--studio')}>
          <AppRoutes />
        </div>
      </main>
      <LoginModal />
    </div>
  );
}

// frontend/src/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';

import AppHeader from '@/components/common/AppHeader.vue';
</script>

<template>
  <AppHeader />
  <main class="app-main" aria-label="Ref2Image Studio 工作区">
    <RouterView />
  </main>
</template>

<style scoped>
.app-main {
  min-height: 100vh;
  padding-top: 64px;
}

@media (max-width: 1080px) {
  .app-main {
    padding-top: 116px;
  }
}
</style>
